name: Mandelbrot

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install cmake libsdl2-dev libsdl2-image-dev
    - name: Build binary
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - uses: actions/upload-artifact@v4
      with:
        name: executable
        path: build/mandelbrot
